# MagicMenu config file
# See https://github.com/onebeastchris/MagicMenu/blob/master/setup.md for all placeholders
# https://github.com/onebeastchris/MagicMenu/blob/master/src/main/resources/config.yml for the default config

# config version - do not change this.
config-version: 2.0

# Should emotes be shown when used to open a menu?
show-emotes: true

# If this is set to true, closing a form will return to the previous form.
go-back: true

# Debug mode: This will spam the console.
debug: false

